let data = [
    {
        "category": "cpu",
        "brand": "Intel",
        "name": "Core i9-9900K",
        "series": "Core i9 9th Gen",
        "processorsType": "Desktop",
        "model": "BX80684I99900K",
        "socketType": "LGA 1151 (300 series)",
        "coreName": "Coffee Lake",
        "numOfCores": "8-Core",
        "numOfThreads": "16",
        "operatingFrequency": "3.6 GHz",
        "maxTurboFrequency": "5.0 GHz",
        "price": "$504.99",
        "description": "Introducing the NEW 9th Gen Intel Core desktop processors the first unlocked mainstream desktop processor. When paired with Intel Optane memory, accelerates the loading and launching of the games you play. With up to 5GHz and 16-way multitasking, take your creativity to the next level with the power you need to create, edit, and share.",
        "imgSrc": "core_i9-9900K.png"
    },
    {
        "category": "cpu",
        "brand": "AMD",
        "name": "Ryzen 5 3600",
        "series": "Ryzen 5 3rd Gen",
        "processorsType": "Desktop",
        "model": "100-100000031BOX",
        "socketType": "Socket AM4",
        "coreName": "Matisse",
        "numOfCores": "6-Core",
        "numOfThreads": "12",
        "operatingFrequency": "3.6 GHz",
        "maxTurboFrequency": "4.2 GHz",
        "price": "$174.99",
        "description": "3rd Gen AMD Ryzen processors are built using the world's most advanced 7nm manufacturing technology. Paired with Wraith coolers, AMD Ryzen processors deliver game-winning performance while keeping your system astonishingly cool and quiet. Ryzen processors neural-net intelligence can adapt to your workload. That's the advantage you gain when you own the world's most advanced processor for gaming.",
        "imgSrc": "ryzen_5_3600.png"
    },
    {
        "category": "cpu",
        "brand": "AMD",
        "name": "Ryzen Threadripper 3990X",
        "series": "Ryzen Threadripper 3rd Gen",
        "processorsType": "Desktop",
        "model": "100-100000163WOF",
        "socketType": "Socket sTRX4",
        "coreName": "",
        "numOfCores": "64-Core",
        "numOfThreads": "128",
        "operatingFrequency": "2.9 GHz",
        "maxTurboFrequency": "Up to 4.3 GHz",
        "price": "$4,063.31",
        "description": "Announced at CES 2020, AMD's 3990X Threadripper processor is a huge leap forward in processing power. The 3990X is designed for creators who need the best rendering performance to enhance productivity and work flow. With 64 cores and 128 threads, you'll be able to run video encoding or rendering applications at blistering speeds and eliminate timeline lag.",
        "imgSrc": "ryzen_threadripper_3990x.png"
    },
    {
        "category": "ram",
        "brand": "CORSAIR",
        "series": "Vengeance RGB Pro",
        "model": "CMW16GX4M2C3200C16",
        "capacity": "16GB (2 x 8GB)",
        "speed": "DDR4 3200 (PC4 25600)",
        "latency": "16",
        "timing": "16-18-18-36",
        "color": "Black",
        "colorLED": "RGB",
        "price": "$99.99",
        "description": "CORSAIR VENGEANCE RGB PRO Series DDR4 memory lights up your PC with mesmerizing dynamic multi-zone RGB lighting, while delivering the best in DDR4 performance and stability. Every module boasts ten individually controlled RGB LEDs, while wire-free design makes installation simple. Take control with CORSAIR iCUE software and completely customize every modules lighting to match your system, or easily synchronize lighting across all your CORSAIR products with Light LINK. A custom designed PCB provides the highest signal quality for the best level of performance and stability on the latest AMD and Intel DDR4 motherboards, while specially screened ICs unlock superior overclocking.",
        "imgSrc": "vengeance_rgb_pro.png"
    },
    {
        "category": "ram",
        "brand": "G.SKILL",
        "series": "TridentZ RGB Series",
        "model": "F4-3200C16D-16GTZR",
        "capacity": "16GB (2 x 8GB)",
        "speed": "DDR4 3200 (PC4 25600)",
        "latency": "16",
        "timing": "16-18-18-38",
        "color": "Black",
        "colorLED": "RGB",
        "price": "$99.99",
        "description": "G.SKILL Trident Z RGB series is one of the worlds most revolutionary RGB lighting DDR4 memory kits. Featuring a complete row of LEDs brilliantly displayed through an uncovered full-length light bar, Trident Z RGB series is capable of displaying a wide range of vivid colors. Along with the strong foundation of G.SKILL overclocking memory development technology, highly screened components, and custom 10-layer PCB, the Trident Z RGB series is the ideal DDR4 solution for building an extremely stylish performance PCs.",
        "imgSrc": "tridentz_rgb_series.png"
    },
    {
        "category": "ram",
        "brand": "G.SKILL",
        "series": "Trident Z Royal Series",
        "model": "F4-3200C16D-16GTRG",
        "capacity": "16GB (2 x 8GB)",
        "speed": "DDR4 3200 (PC4 25600)",
        "latency": "16",
        "timing": "16-18-18-38",
        "color": "Gold",
        "colorLED": "RGB",
        "price": "$124.99",
        "description": "Trident Z Royal is the latest addition to the Trident Z flagship family and features a crown jewel design. Meticulously crafted to display just the right amount of light refraction, the crystalline light bar scatters the RGB colors in a magnificent display of LED lighting. Mirroring the high-class light bar design, polished aluminum heatspreaders of gold or silver colors cools the memory modules in the award-winning classic Trident Z tri-fin design.",
        "imgSrc": "trident_z_royal_series.png"
    },
    {
        "category": "videoCard",
        "brand": "EVGA",
        "series": "",
        "model": "08G-P4-3172-KR",
        "interface": "PCI Express 3.0",
        "chipset": "NVIDIA",
        "gpu": "GeForce RTX 2070 SUPER",
        "memorySize": "8GB",
        "memoryType": "GDDR6",
        "maxResolution": "7680 x 4320",
        "cooler": "Double Fans",
        "maxGPULength": "270 mm",
        "cardDimensions": "10.62\" x 4.38\"",
        "price": "$539.99",
        "description": "The EVGA GeForce RTX 20-Series Graphics Cards are powered by the all-new NVIDIA Turing architecture to give you incredible new levels of gaming realism, speed, power efficiency, and immersion. With the EVGA GeForce RTX 20-Series gaming cards you get the best gaming experience with next generation graphics performance, ice cold cooling, and advanced overclocking features with the all new EVGA Precision X1 software.",
        "imgSrc": "evga_08G-P4-3172-KR.png"
    },
    {
        "category": "videoCard",
        "brand": "SAPPHIRE",
        "series": "PULSE",
        "model": "100416P8GL",
        "interface": "PCI Express 4.0 x16",
        "chipset": "AMD",
        "gpu": "Radeon RX 5700 XT",
        "memorySize": "8GB",
        "memoryType": "GDDR6",
        "maxResolution": "HDMI: 4096 x 2160 @ 60 Hz\r\nDisplayPort1.4: 5120 x 2880 @ 60 Hz",
        "cooler": "Double Fans",
        "maxGPULength": "254 mm",
        "cardDimensions": "10.00\" x 5.31\"",
        "price": "$399.99",
        "description": "The SAPPHIRE PULSE RX 5700 XT offers great performance at the affordable price point that every gamer needs. With quality components and a robust digital power design, the PULSE RX 5700 XT delivers exceptional 1440p performance and high-fidelity gaming powered by AMDs new extreme RDNA architecture. Its finely-tuned Dual-X Cooling Technology not only keeps the GPU, memory and VRM components cool, but also at a very low noise level. The all-aluminum backplate provides additional rigidity that guarantees nothing bends and dust stays out, and it also helps cool your card by increasing heat dissipation. Pivotal SAPPHIRE features like the Quick Connect Fan, Dual Bios Support and Power Fuse are all readily available to keep your GPU running smooth and silent. Get ready to experience next-level gaming performance and welcome the PULSE RX 5700 XT as the new integral heart of your PC!",
        "imgSrc": "sapphire_100416p8gl.png"
    },
    {
        "category": "videoCard",
        "brand": "MSI",
        "series": "",
        "model": "RTX 2080 Ti VENTUS GP",
        "interface": "PCI Express 3.0 x16",
        "chipset": "NVIDIA",
        "gpu": "GeForce RTX 2080 Ti",
        "memorySize": "11GB",
        "memoryType": "GDDR6",
        "maxResolution": "7680 x 4320",
        "cooler": "Double Fans",
        "maxGPULength": "268 mm",
        "cardDimensions": "10.55\" x 4.41\"",
        "price": "$1,079.99",
        "description": "A fresh new dual fan design, VENTUS proudly displays its industrial shapes in neutral colors to fit any build. Double Ball Bearings give the unique MSI customized Fans a strong and lasting core for years of smooth gaming. The smoothest, fastest and most exciting gaming experience ever by eliminating screen tearing, display stutter and input lag.",
        "imgSrc": "msi_geforce_rtx_2080_ti.png"
    },
    {
        "category": "videoCard",
        "brand": "HP",
        "series": "",
        "model": "E1C63AA",
        "interface": "PCI Express 3.0 x16",
        "chipset": "AMD",
        "gpu": "Radeon HD 8350",
        "memorySize": "1GB",
        "memoryType": "DDR3",
        "maxResolution": "2560 x 1600",
        "cooler": "",
        "maxGPULength": "",
        "cardDimensions": "6.15\" x 2.72\"",
        "price": "$23.71",
        "description": "Get stable 2D and advanced 3D graphics performance from the AMD Radeon HD 8350 1 GB PCIe x16 DH GFX, a low profile, PCI Express x16 graphics add-in card based on the AMD Radeon HD 8350 GPU, great for Web conferencing or video and photo editing.",
        "imgSrc": "hp_e1c63aa.png"
    }
];

function load(){
    return data;
}